# .pre-commit-config.yaml
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        exclude_types: [svg, json]

      - id: end-of-file-fixer
        exclude_types: [svg, json]

      - id: check-yaml

  # - repo: https://github.com/igorshubovych/markdownlint-cli
  #   rev: v0.43.0
  #   hooks:
  #   - id: markdownlint
  #     files: readme.md
  #     args:
  #       - --fix
  #       - --disable=MD013
